export const firebaseResponseError ={
    "auth/wrong-password": "Le mot de passe est invalide ou l'utilisateur n'a pas de mot de passe.",
    "auth/claims-too-large": "La charge utile de revendications fournie à setCustomUserClaims() dépasse la taille maximale autorisée de 1 000 octets.",
    "auth/email-already-exists": "L'e-mail fourni est déjà utilisé par un utilisateur existant. Chaque utilisateur doit avoir un e-mail unique.",
    "auth/id-token-expired": "Le jeton d'identification Firebase fourni a expiré.",
    "auth/id-token-revoked": "Le jeton d'identification Firebase a été révoqué.",
    "auth/insufficient-permission": "Les informations d'identification utilisées pour initialiser le SDK Admin ne disposent pas des autorisations suffisantes pour accéder à la ressource d'authentification demandée. Reportez-vous à Configurer un projet Firebase pour obtenir de la documentation sur la manière de générer des informations d'identification avec les autorisations appropriées et de les utiliser pour s'authentifier les SDK d'administration.",
    "auth/invalid-argument": "Un argument invalide a été fourni à une méthode d'authentification. Le message d'erreur doit contenir des informations supplémentaires.",
    "auth/invalid-claims": "Les attributs de réclamation personnalisés fournis à setCustomUserClaims() ne sont pas valides.",
    "auth/invalid-creation-time": "L'heure de création doit être une chaîne de date UTC valide.",
    "auth/invalid-disabled-field": "La valeur fournie pour la propriété de l'utilisateur désactivé n'est pas valide. Il doit s'agir d'un booléen.",
    "auth/invalid-display-name": "La valeur fournie pour la propriété utilisateur displayName n'est pas valide. Il doit s'agir d'une chaîne non vide.",
    "auth/invalid-email-verified": "La valeur fournie pour la propriété utilisateur emailVerified n'est pas valide. Il doit s'agir d'un booléen.",
    "auth/invalid-hash-algorithm": "L'algorithme de hachage doit correspondre à l'une des chaînes de la liste des algorithmes pris en charge.",
    "auth/invalid-hash-block-size": "La taille du bloc de hachage doit être un nombre valide.",
    "auth/invalid-hash-derived-key-length": "La longueur de la clé dérivée du hachage doit être un nombre valide.",
    "auth/invalid-hash-key": "La clé de hachage doit être un tampon d'octets valide.",
    "auth/invalid-hash-memory-cost": "Le coût de la mémoire de hachage doit être un nombre valide.",
    "auth/invalid-hash-parallelization": "La parallélisation du hachage doit être un nombre valide.",
    "auth/invalid-hash-rounds": "Les tours de hachage doivent être un nombre valide.",
    "auth/invalid-hash-salt-separator": "Le champ séparateur de sel de l'algorithme de hachage doit être un tampon d'octets valide.",
    "auth/invalid-id-token": "Le jeton d'identification fourni n'est pas un jeton d'identification Firebase valide.",
    "auth/invalid-last-sign-in-time": "L'heure de la dernière connexion doit être une chaîne de date UTC valide.",
    "auth/invalid-page-token": "Le jeton de page suivante fourni dans listUsers() n'est pas valide. Il doit s'agir d'une chaîne non vide valide.",
    "auth/invalid-password": "La valeur fournie pour la propriété utilisateur du mot de passe n'est pas valide. Il doit s'agir d'une chaîne d'au moins six caractères.",
    "auth/invalid-password-hash": "Le hachage du mot de passe doit être un tampon d'octets valide.",
    "auth/invalid-password-salt": "Le mot de passe salt doit être un tampon d'octets valide",
    "auth/invalid-photo-url": "La valeur fournie pour la propriété utilisateur photoURL n'est pas valide. Il doit s'agir d'une URL de chaîne.",
    "auth/invalid-provider-data": "Le providerData doit être un tableau valide d'objets UserInfo.",
    "auth/invalid-oauth-responsetype": "Un seul type de réponse OAuth doit être défini sur vrai.",
    "auth/invalid-session-cookie-duration": "La durée du cookie de session doit être un nombre valide en millisecondes entre 5 minutes et 2 semaines.",
    "auth/invalid-uid": "L'uid fourni doit être une chaîne non vide d'au plus 128 caractères.",
    "auth/invalid-user-import": "L'enregistrement de l'utilisateur à importer n'est pas valide.",
    "auth/maximum-user-count-exceeded": "Le nombre maximum d'utilisateurs autorisés à importer a été dépassé.",
    "auth/missing-hash-algorithm": "L'importation d'utilisateurs avec des hachages de mot de passe nécessite que l'algorithme de hachage et ses paramètres soient fournis.",
    "auth/missing-uid": "Un identifiant uid est requis pour l'opération en cours.",
    "auth/missing-oauth-client-secret": "Le secret du client de configuration OAuth est requis pour activer le flux de code OIDC.",
    "auth/phone-number-already-exists": "Le numéro de téléphone fourni est déjà utilisé par un utilisateur existant. Chaque utilisateur doit avoir un numéro de téléphone unique.",
    "auth/project-not-found": "Aucun projet Firebase n'a été trouvé pour les informations d'identification utilisées pour initialiser les SDK d'administration. Reportez-vous à Configurer un projet Firebase pour savoir comment générer des informations d'identification pour votre projet et l'utiliser pour authentifier le SDK d'administration.",
    "auth/reserved-claims": "Une ou plusieurs revendications utilisateur personnalisées fournies à setCustomUserClaims() sont réservées. Par exemple, les revendications spécifiques OIDC telles que (sub, iat, iss, exp, aud, auth_time, etc.) ne doivent pas être utilisées comme clés pour les revendications personnalisées.",
    "auth/session-cookie-expired": "Le cookie de session Firebase fourni a expiré.",
    "auth/session-cookie-revoked": "Le cookie de session Firebase a été révoqué.",
    "auth/uid-already-exists": "L'uid fourni est déjà utilisé par un utilisateur existant. Chaque utilisateur doit avoir un uid unique.",
    "auth/admin-restricted-operation": "Cette opération est réservée aux administrateurs uniquement.",
    "auth/app-not-authorized": "Cette application, identifiée par le domaine où elle est hébergée, n'est pas autorisée à utiliser Firebase Authentication avec la clé API fournie. Vérifiez la configuration de votre clé dans la console API Google.",
    "auth/app-not-installed": "L'application mobile demandée correspondant à l'identifiant (nom du package Android ou ID du bundle iOS) fourni n'est pas installée sur cet appareil.",
    "auth/captcha-check-failed": "Le jeton de réponse reCAPTCHA fourni est invalide, expiré, déjà utilisé ou le domaine qui lui est associé ne correspond pas à la liste des domaines en liste blanche.",
    "auth/code-expired": "Le code SMS a expiré. Veuillez renvoyer le code de vérification pour réessayer.",
    "auth/cordova-not-ready": "Le framework Cordova n'est pas prêt.",
    "auth/cors-unsupported": "Ce navigateur n'est pas pris en charge.",
    "auth/credential-already-in-use": "Cet identifiant est déjà associé à un autre compte utilisateur.",
    "auth/custom-token-mismatch": "Le jeton personnalisé correspond à une audience différente.",
    "auth/requires-recent-login": "Cette opération est sensible et nécessite une authentification récente. Reconnectez-vous avant de réessayer cette requête.",
    "auth/dependent-sdk-initialized-before-auth": "Un autre SDK Firebase a été initialisé et essaie d'utiliser Auth avant qu'Auth ne soit initialisé. Assurez-vous d'appeler `initializeAuth` ou `getAuth` avant de démarrer tout autre SDK Firebase. ",
    "auth/dynamic-link-not-activated": "Veuillez activer les liens dynamiques dans la console Firebase et accepter les termes et conditions.",
    "auth/email-change-needs-verification": "Les utilisateurs multi-facteurs doivent toujours avoir une adresse e-mail vérifiée.",
    "auth/email-already-in-use": "L'adresse e-mail est déjà utilisée par un autre compte.",
    "auth/emulator-config-failed": "L'instance d'Auth a déjà été utilisée pour passer un appel réseau. Auth ne peut plus être configuré pour utiliser l'émulateur. Essayez d'appeler 'connectAuthEmulator()' plus tôt.",
    "auth/expired-action-code": "Le code d'action a expiré.",
    "auth/cancelled-popup-request": "Cette opération a été annulée en raison de l'ouverture d'une autre fenêtre contextuelle en conflit.",
    "auth/internal-error": "Une erreur d'authentification interne s'est produite.",
    "auth/invalid-app-credential": "La demande de vérification du téléphone contient un vérificateur d'application invalide. La réponse du jeton reCAPTCHA est invalide ou expirée.",
    "auth/invalid-app-id": "L'identifiant de l'application mobile n'est pas enregistré pour le projet en cours.",
    "auth/invalid-user-token": "Les informations d'identification de cet utilisateur ne sont pas valides pour ce projet. Cela peut se produire si le jeton de l'utilisateur a été falsifié ou si l'utilisateur n'est pas pour le projet associé à cette clé API. ",
    "auth/invalid-auth-event": "Une erreur d'authentification interne s'est produite.",
    "auth/invalid-verification-code": "Le code de vérification par SMS utilisé pour créer l'identifiant d'authentification du téléphone n'est pas valide. Veuillez renvoyer le SMS du code de vérification et assurez-vous d'utiliser le code de vérification fourni par l'utilisateur.",
    "auth/invalid-continue-uri": "L'URL de continuation fournie dans la requête n'est pas valide.",
    "auth/invalid-cordova-configuration": "Les plugins Cordova suivants doivent être installés pour activer la connexion OAuth : cordova-plugin-buildinfo, cordova-universal-links-plugin, cordova-plugin-browsertab, cordova-plugin-inappbrowser et cordova-plugin-customurlscheme.",
    "auth/invalid-custom-token": "Le format du jeton personnalisé est incorrect. Veuillez consulter la documentation.",
    "auth/invalid-dynamic-link-domain": "Le domaine de lien dynamique fourni n'est pas configuré ou autorisé pour le projet en cours.",
    "auth/invalid-email": "L'adresse e-mail est mal formatée.",
    "auth/invalid-emulator-scheme": "L'URL de l'émulateur doit commencer par un schéma valide (http:// ou https://).",
    "auth/invalid-api-key": "Votre clé API n'est pas valide, veuillez vérifier que vous l'avez correctement copiée.",
    "auth/invalid-cert-hash": "Le hachage du certificat SHA-1 fourni n'est pas valide.",
    "auth/invalid-credential": "L'identifiant d'authentification fourni est incorrect ou a expiré.",
    "auth/invalid-message-payload": "Le modèle d'e-mail correspondant à cette action contient des caractères invalides dans son message. Veuillez corriger en accédant à la section Modèles d'e-mail d'authentification dans la console Firebase.",
    "auth/invalid-multi-factor-session": "La requête ne contient pas de preuve valide de la connexion réussie du premier facteur.",
    "auth/invalid-oauth-provider": "EmailAuthProvider n'est pas pris en charge pour cette opération. Cette opération ne prend en charge que les fournisseurs OAuth.",
    "auth/invalid-oauth-client-id": "L'ID client OAuth fourni est invalide ou ne correspond pas à la clé API spécifiée.",
    "auth/unauthorized-domain": "Ce domaine n'est pas autorisé pour les opérations OAuth pour votre projet Firebase. Modifiez la liste des domaines autorisés depuis la console Firebase.",
    "auth/invalid-action-code": "Le code d'action n'est pas valide. Cela peut se produire si le code est mal formé, a expiré ou a déjà été utilisé.",
    "auth/invalid-persistence-type": "Le type de persistance spécifié n'est pas valide. Il ne peut être que local, session ou aucun.",
    "auth/invalid-phone-number": "Le format du numéro de téléphone fourni est incorrect. Veuillez entrer le numéro de téléphone dans un format qui peut être analysé au format E.164. Les numéros de téléphone E.164 sont écrits au format [ +][code pays][numéro d'abonné avec indicatif régional]",
    "auth/invalid-provider-id": "L'ID de fournisseur spécifié n'est pas valide.",
    "auth/invalid-recipient-email": "L'e-mail correspondant à cette action n'a pas pu être envoyé car l'adresse e-mail du destinataire fournie n'est pas valide.",
    "auth/invalid-sender": "Le modèle d'e-mail correspondant à cette action contient un e-mail ou un nom d'expéditeur non valide. Veuillez corriger en accédant à la section Modèles d'e-mail d'authentification dans la console Firebase.",
    "auth/invalid-verification-id": "L'ID de vérification utilisé pour créer l'identifiant d'authentification par téléphone n'est pas valide.",
    "auth/invalid-tenant-id": "L'ID de locataire de l'instance Auth n'est pas valide.",
    "auth/missing-android-pkg-name": "Un nom de package Android doit être fourni si l'application Android doit être installée.",
    "auth/auth-domain-config-required": "Assurez-vous d'inclure authDomain lors de l'appel de firebase.initializeApp(), en suivant les instructions de la console Firebase.",
    "auth/missing-app-credential": "Il manque une assertion de vérificateur d'application dans la demande de vérification par téléphone. Un jeton de réponse reCAPTCHA doit être fourni.",
    "auth/missing-verification-code": "L'identifiant d'authentification du téléphone a été créé avec un code de vérification par SMS vide.",
    "auth/missing-continue-uri": "Une URL de continuation doit être fournie dans la requête.",
    "auth/missing-iframe-start": "Une erreur d'authentification interne s'est produite.",
    "auth/missing-ios-bundle-id": "Un ID de bundle iOS doit être fourni si un ID App Store est fourni.",
    "auth/missing-or-invalid-nonce": "La requête ne contient pas de nonce valide. Cela peut se produire si le hachage SHA-256 du nonce brut fourni ne correspond pas au nonce haché dans la charge utile du jeton d'ID.",
    "auth/missing-multi-factor-info": "Aucun deuxième identifiant de facteur n'est fourni.",
    "auth/missing-multi-factor-session": "Il manque à la demande la preuve de la connexion réussie du premier facteur.",
    "auth/missing-phone-number": "Pour envoyer des codes de vérification, fournissez un numéro de téléphone au destinataire.",
    "auth/missing-verification-id": "L'identifiant d'authentification par téléphone a été créé avec un ID de vérification vide.",
    "auth/app-deleted": "Cette instance de FirebaseApp a été supprimée.",
    "auth/multi-factor-info-not-found": "L'utilisateur n'a pas de deuxième facteur correspondant à l'identifiant fourni.",
    "auth/multi-factor-auth-required": "Une preuve de propriété d'un deuxième facteur est requise pour terminer la connexion.",
    "auth/account-exists-with-different-credential": "Un compte existe déjà avec la même adresse e-mail mais des identifiants de connexion différents. Connectez-vous en utilisant un fournisseur associé à cette adresse e-mail.",
    "auth/network-request-failed": "Une erreur d'authentification réseau (telle qu'un délai d'attente, une connexion interrompue ou un hôte inaccessible) s'est produite.",
    "auth/no-auth-event": "Une erreur d'authentification interne s'est produite.",
    "auth/no-such-provider": "L'utilisateur n'était pas lié à un compte chez le fournisseur donné.",
    "auth/null-user": "Un objet utilisateur nul a été fourni comme argument pour une opération nécessitant un objet utilisateur non nul.",
    "auth/operation-not-allowed": "Le fournisseur de connexion indiqué est désactivé pour ce projet Firebase. Activez-le dans la console Firebase, sous l'onglet Méthode de connexion de la section Auth.",
    "auth/operation-not-supported-in-this-environment": "Cette opération n'est pas prise en charge dans l'environnement sur lequel cette application s'exécute. 'location.protocol' doit être http, https ou chrome-extension et le stockage Web doit être activé.",
    "auth/popup-blocked": "Impossible d'établir une connexion avec la popup. Elle a peut-être été bloquée par le navigateur.",
    "auth/popup-closed-by-user": "La popup a été fermée par l'utilisateur avant de finaliser l'opération.",
    "auth/provider-already-linked": "L'utilisateur ne peut être lié qu'à une seule identité pour le fournisseur donné.",
    "auth/quota-exceeded": "Le quota du projet pour cette opération a été dépassé.",
    "auth/redirect-cancelled-by-user": "L'opération de redirection a été annulée par l'utilisateur avant la finalisation.",
    "auth/redirect-operation-pending": "Une opération de redirection de connexion est déjà en attente.",
    "auth/rejected-credential": "La requête contient des informations d'identification mal formées ou incompatibles.",
    "auth/second-factor-already-in-use": "Le deuxième facteur est déjà inscrit sur ce compte.",
    "auth/maximum-second-factor-count-exceeded": "Le nombre maximal autorisé de seconds facteurs sur un utilisateur a été dépassé.",
    "auth/tenant-id-mismatch": "L'ID de locataire fourni ne correspond pas à l'ID de locataire de l'instance Auth",
    "auth/timeout": "L'opération a expiré.",
    "auth/user-token-expired": "Les informations d'identification de l'utilisateur ne sont plus valides. L'utilisateur doit se reconnecter.",
    "auth/too-many-requests": "Nous avons bloqué toutes les requêtes de cet appareil en raison d'une activité inhabituelle. Réessayez plus tard.",
    "auth/unauthorized-continue-uri": "Le domaine de l'URL de continuation n'est pas sur la liste blanche. Veuillez ajouter le domaine à la liste blanche dans la console Firebase.",
    "auth/unsupported-first-factor": "L'inscription d'un deuxième facteur ou la connexion avec un compte multifacteur nécessite une connexion avec un premier facteur pris en charge.",
    "auth/unsupported-persistence-type": "L'environnement actuel ne prend pas en charge le type de persistance spécifié.",
    "auth/unsupported-tenant-operation": "Cette opération n'est pas prise en charge dans un contexte multi-tenant.",
    "auth/unverified-email": "L'opération nécessite un e-mail vérifié.",
    "auth/user-cancelled": "L'utilisateur n'a pas accordé à votre application les autorisations demandées.",
    "auth/user-not-found": "Aucun enregistrement d'utilisateur ne correspond à cet identifiant. L'utilisateur a peut-être été supprimé.",
    "auth/user-disabled": "Le compte utilisateur a été désactivé par un administrateur.",
    "auth/user-mismatch": "Les informations d'identification fournies ne correspondent pas à l'utilisateur précédemment connecté.",
    "auth/weak-password": "Le mot de passe doit comporter au moins 6 caractères.",
    "auth/web-storage-unsupported": "Ce navigateur n'est pas pris en charge ou les cookies et données tiers peuvent être désactivés.",
    "auth/already-initialized": "initializeAuth() a déjà été appelé avec différentes options. Pour éviter cette erreur, appelez initializeAuth() avec les mêmes options que lorsqu'il a été appelé à l'origine, ou appelez getAuth() pour renvoyer le fichier déjà initialisé exemple."
}